# Form implementation generated from reading ui file 'src/ui/add_student.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_user_dialog(object):
    def setupUi(self, add_user_dialog):
        add_user_dialog.setObjectName("add_user_dialog")
        add_user_dialog.resize(829, 264)
        self.horizontalLayout = QtWidgets.QHBoxLayout(add_user_dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profile_image_preview = QtWidgets.QLabel(parent=add_user_dialog)
        self.profile_image_preview.setMinimumSize(QtCore.QSize(200, 200))
        self.profile_image_preview.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.profile_image_preview.setObjectName("profile_image_preview")
        self.horizontalLayout.addWidget(self.profile_image_preview)
        self.profile_layout = QtWidgets.QVBoxLayout()
        self.profile_layout.setObjectName("profile_layout")
        self.profile_name_layout = QtWidgets.QHBoxLayout()
        self.profile_name_layout.setObjectName("profile_name_layout")
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.profile_name_layout.addItem(spacerItem)
        self.profile_name_label = QtWidgets.QLabel(parent=add_user_dialog)
        self.profile_name_label.setObjectName("profile_name_label")
        self.profile_name_layout.addWidget(self.profile_name_label)
        self.profile_name_input = QtWidgets.QLineEdit(parent=add_user_dialog)
        self.profile_name_input.setObjectName("profile_name_input")
        self.profile_name_layout.addWidget(self.profile_name_input)
        self.profile_layout.addLayout(self.profile_name_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.profile_layout.addItem(spacerItem1)
        self.profile_image_layout = QtWidgets.QHBoxLayout()
        self.profile_image_layout.setObjectName("profile_image_layout")
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.profile_image_layout.addItem(spacerItem2)
        self.profile_image_label = QtWidgets.QLabel(parent=add_user_dialog)
        self.profile_image_label.setObjectName("profile_image_label")
        self.profile_image_layout.addWidget(self.profile_image_label)
        self.profile_image_input = QtWidgets.QLineEdit(parent=add_user_dialog)
        self.profile_image_input.setReadOnly(True)
        self.profile_image_input.setObjectName("profile_image_input")
        self.profile_image_layout.addWidget(self.profile_image_input)
        self.profile_image_browse = QtWidgets.QPushButton(parent=add_user_dialog)
        self.profile_image_browse.setObjectName("profile_image_browse")
        self.profile_image_layout.addWidget(self.profile_image_browse)
        self.profile_layout.addLayout(self.profile_image_layout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=add_user_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.profile_layout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.profile_layout)

        self.retranslateUi(add_user_dialog)
        self.buttonBox.accepted.connect(add_user_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(add_user_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_user_dialog)

    def retranslateUi(self, add_user_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_user_dialog.setWindowTitle(_translate("add_user_dialog", "Add Student"))
        self.profile_image_preview.setText(_translate("add_user_dialog", "Image Preview"))
        self.profile_name_label.setText(_translate("add_user_dialog", "Name: "))
        self.profile_image_label.setText(_translate("add_user_dialog", "Image: "))
        self.profile_image_browse.setText(_translate("add_user_dialog", "Browse..."))
